sources:
  - name: Academy
    transforms:
      - filterSchema:
          - Query.!server
      # TODO: enabling results in error
      #- encapsulate:
      #    applyTo:
      #      query: true
      #      mutation: false
      #      subscription: false
      #- rename:
      #    - from:
      #        type: Query
      #        field: items
      #      to:
      #        type: Query
      #        field: academy
    handler:
      graphql:
        endpoint: http://localhost:8055/graphql
        schemaHeaders:
          # Directus token goes after Bearer
          Authorization: Bearer
        operationHeaders:
          Authorization: Bearer
        # TODO: enabling results in error
        batch: false

transforms:
  #- namingConvention:
      # TODO: Causes issue with union types
      # typeNames: pascalCase
      # enumValues: upperCase
      # fieldNames: camelCase

serve:
  port: 5000